### ISSUE TITLE
Small question in mouse direction detection code

### ISSUE THREAD

**Issue by yaodingyd** [liuyunzhuge/blog#1]
Thanks for this wonderful post!
Small question, in your demo.html line 106, why  is "$content[0].offsetWidth;"  for reflow? you just get a static property.

**Comment by liuyunzhuge** [comment]
$content[0].offsetWidth虽然没有任何赋值操作的，但它依然会造成对DOM属性的读取，这种行为就会引起reflow。
http://www.ruanyifeng.com/blog/2015/09/web-page-performance-in-depth.html
