### ISSUE TITLE
关于您的一篇文章 3种web会话管理的方式

### ISSUE THREAD

**Issue by Coooooooola** [liuyunzhuge/blog#3]
里面有说到基于客户端保存凭证，服务端不需要保存只需要验证凭证的技术。
但是假如用户修改了密码或者取消记住密码，原来的凭证依然有效，所以你必须得用一个数据库去记录那些凭证是否有效。因为存放于客户端的凭证永远也无法知道最新状态。
那么这种方式不如直接用session id 的方式。请问有什么解决方法吗？

**Comment by liuyunzhuge** [comment]
存数据库或者存redis，给凭证设置一个过期时间。

**Comment by Coooooooola** [comment]
既然都要存数据库～那为何不直接用 session id
